### ISSUE TITLE
NA/NaN argument

### ISSUE THREAD

**Issue by JosephPParker** [vragh/seqvisr#2]
Thanks for making this tool.  I have installed and tried to use msavisr but have not been able to get an output.
Using:

- R 3.5.1
- seqvisr 0.2.5

I have this MSA from Clustal Omega which I have saved as a FASTA file.
[MSA.fasta.txt](https://github.com/vragh/seqvisr/files/7953256/MSA.fasta.txt)

But when I use it in the msavisr command with Hsap as the reference sequence, it always results in the following error:

(curpos + 1):(nextpos - 1) : NA/NaN argument

Can you advise me what I'm doing wrong?  Is it an issue with the file?

**Comment by JosephPParker** [comment]
Never mind, I figured it out.  
It wasn't enough to save as a FASTA file, the output on Clustal Omega had to be set to FASTA.
Thanks for your time anyway, and for the useful tool.

**Comment by vragh** [comment]
Hi, yes exactly, the file you'd shared here was in the `CLUSTAL` format. Glad you were able to sort the issue out quickly!!
